version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/" # ルートディレクトリにDockerfileがある場合
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "docker"
    directory: "/" # ルートディレクトリにDockerfile.alpineがある場合
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
