# 動作チェック用のdocker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:cached
    ports:
      - "8080:80"
    working_dir: /app
    command: ["php", "-S", "0.0.0.0:80", "-t", "./public"]