name: イメージの作成テスト

on:
  pull_request: 
    branches: 
      - main
  push:
    branches-ignore: 
      - main
    paths: 
      - "**/Dockerfile*"
      - "./conf.d/*"
  workflow_dispatch:

permissions:
    contents: read
    packages: read

jobs:
    generate-serial:
        runs-on: ubuntu-24.04
        outputs:
            serial: ${{ steps.serial.outputs.serial }}
        steps:
            - name: シリアル値の作成(タグ用)
              id: serial
              run: echo "serial=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

    build:
        needs: generate-serial
        strategy:
            matrix:
                include:
                    # 従来のUbuntuベースイメージ
                    - platform: amd64
                      runner: ubuntu-24.04
                      dockerfile: Dockerfile
                      suffix: ubuntu
                    # Alpineベースイメージ
                    - platform: amd64
                      runner: ubuntu-24.04
                      dockerfile: Dockerfile.alpine
                      suffix: alpine

        runs-on: ${{ matrix.runner }}
        timeout-minutes: 10
        steps:
            - name: リポジトリのチェックアウト
              uses: actions/checkout@v4

            - name: Docker ビルドと後始末
              run: |
                REPO="test:${{ needs.generate-serial.outputs.serial }}-${{ matrix.suffix }}"
                docker build -t "${REPO}" -f ${{ matrix.dockerfile }} .
                build_status=$?
                docker rmi "${REPO}" || true
                exit $build_status


        
    