name: イメージの作成と公開

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    generate-serial:
        runs-on: ubuntu-24.04
        outputs:
            serial: ${{ steps.serial.outputs.serial }}
        steps:
            - name: シリアル値の作成(タグ用)
              id: serial
              run: echo "serial=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

    build:
        needs: generate-serial
        strategy:
            matrix:
                platform: [linux/amd64, linux/arm64]
                runner: [ubuntu-24.04, ubuntu-24.04-arm]
                exclude:
                    - platform: linux/amd64
                      runner: ubuntu-24.04-arm
                    - platform: linux/arm64
                      runner: ubuntu-24.04
        runs-on: ${{ matrix.runner }}
        timeout-minutes: 10
        steps:
            - name: リポジトリのチェックアウト
              uses: actions/checkout@v4

            - name: GHCR向けのログイン
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: QEMU のセットアップ
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: ${{ matrix.platform }}

            - name: Docker Buildx のセットアップ
              uses: docker/setup-buildx-action@v3

            - name: Docker Buildx のビルドとプッシュ
              uses: docker/build-push-action@v6
              with:
                  context: .
                  provenance: false
                  push: true
                  platforms: ${{ matrix.platform }}
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.generate-serial.outputs.serial }}
                  cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache
                  cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache,mode=max
