name: イメージの作成と公開

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    generate-serial:
        runs-on: ubuntu-24.04
        outputs:
            serial: ${{ steps.serial.outputs.serial }}
        steps:
            - name: シリアル値の作成(タグ用)
              id: serial
              run: echo "serial=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

    build:
        needs: generate-serial
        strategy:
            matrix:
                platform: [amd64, arm64]
                runner: [ubuntu-24.04, ubuntu-24.04-arm]
                exclude:
                    - platform: amd64
                      runner: ubuntu-24.04-arm
                    - platform: arm64
                      runner: ubuntu-24.04
        runs-on: ${{ matrix.runner }}
        timeout-minutes: 10
        steps:
            - name: リポジトリのチェックアウト
              uses: actions/checkout@v4

            - name: GHCR向けのログイン
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: QEMU のセットアップ
              uses: docker/setup-qemu-action@v3
              with:
                  platforms: linux/${{ matrix.platform }}

            - name: Docker Buildx のセットアップ
              uses: docker/setup-buildx-action@v3

            - name: Docker Buildx のビルドとプッシュ
              uses: docker/build-push-action@v6
              with:
                  context: .
                  provenance: false
                  push: true
                  platforms: linux/${{ matrix.platform }}
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}-${{ matrix.platform }}
                      ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ needs.generate-serial.outputs.serial }}-${{ matrix.platform }}
                  cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache
                  cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:cache,mode=max
    merge:
        # ビルド結果を基に、ひとつのイメージタグとしてマージする
        # 付与するのはシリアル値とlatest
        needs: 
          - build
          - generate-serial
        runs-on: ubuntu-24.04
        steps:
            - name: GHCR向けのログイン
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: マニフェストを作成
              id: manifest
              run: |
                  REPO="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
                  TAG="${{ needs.generate-serial.outputs.serial }}"
                  for item in latest "${TAG}"; do
                  docker manifest create "${REPO}:${item}" \
                      "${REPO}:${TAG}-amd64" \
                      "${REPO}:${TAG}-arm64" \
                      --amend "${REPO}:${TAG}-amd64" \
                      --amend "${REPO}:${TAG}-arm64"
                  done
